"use client";

import { useState } from "react";
import ChatInput from "./ChatInput";
import ChatMessage from "./ChatMessage";

interface Message {
  id: number;
  role: "user" | "assistant";
  content: string;
  source?: {
    title: string;
    page: number;
  };
}

const initialMessages: Message[] = [
  {
    id: 1,
    role: "assistant",
    content:
      "Hello! I can answer questions based on the documents in this notebook.",
    source: {
      title: "Java Fundamentals.pdf",
      page: 1,
    },
  },
];

export default function ChatWindow() {
  const [messages, setMessages] =
    useState<Message[]>(initialMessages);

  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  function handleSend() {
  const trimmedInput = input.trim();

  if (!trimmedInput || isLoading) {
    return;
  }

  const userMessage: Message = {
    id: Date.now(),
    role: "user",
    content: trimmedInput,
  };

  setMessages((currentMessages) => [
    ...currentMessages,
    userMessage,
  ]);

  setInput("");
  setIsLoading(true);

  setTimeout(() => {
    const assistantMessage: Message = {
      id: Date.now() + 1,
      role: "assistant",
      content:
        "This is a demo response. Later, this message will be generated by our RAG system using the documents in this notebook.",
      source: {
        title: "Java Fundamentals.pdf",
        page: 12,
      },
    };

    setMessages((currentMessages) => [
      ...currentMessages,
      assistantMessage,
    ]);

    setIsLoading(false);
  }, 800);
}

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="flex-1 overflow-auto p-6">
        <div className="mx-auto max-w-3xl space-y-6">
          {messages.map((message) => (
            <ChatMessage
              key={message.id}
              role={message.role}
              content={message.content}
              source={message.source}
            />
          ))}
        </div>
      </div>

      <ChatInput
  value={input}
  onChange={setInput}
  onSend={handleSend}
  isLoading={isLoading}
/>
    </div>
  );
}