"use client";

import { useState } from "react";
import ChatMessage from "./ChatMessage";

interface Message {
  id: number;
  role: "user" | "assistant";
  content: string;
  source?: {
    title: string;
    page: number;
  };
}

const initialMessages: Message[] = [
  {
    id: 1,
    role: "assistant",
    content:
      "Hello! I can answer questions based on the documents in this notebook.",
    source: {
      title: "Java Fundamentals.pdf",
      page: 1,
    },
  },
];

export default function ChatWindow() {
  const [messages, setMessages] =
    useState<Message[]>(initialMessages);

  const [input, setInput] = useState("");

  function handleSend() {
    const trimmedInput = input.trim();

    if (!trimmedInput) {
      return;
    }

    const userMessage: Message = {
      id: Date.now(),
      role: "user",
      content: trimmedInput,
    };

    setMessages((currentMessages) => [
      ...currentMessages,
      userMessage,
    ]);

    setInput("");

    setTimeout(() => {
      const assistantMessage: Message = {
        id: Date.now() + 1,
        role: "assistant",
        content:
          "This is a demo response. Later, this message will be generated by our RAG system using the documents in this notebook.",
        source: {
          title: "Java Fundamentals.pdf",
          page: 12,
        },
      };

      setMessages((currentMessages) => [
        ...currentMessages,
        assistantMessage,
      ]);
    }, 800);
  }

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="flex-1 overflow-auto p-6">
        <div className="mx-auto max-w-3xl space-y-6">
          {messages.map((message) => (
            <ChatMessage
              key={message.id}
              role={message.role}
              content={message.content}
              source={message.source}
            />
          ))}
        </div>
      </div>

      <div className="border-t p-4">
        <div className="mx-auto flex max-w-3xl gap-2">
          <input
            type="text"
            value={input}
            onChange={(event) => setInput(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") {
                handleSend();
              }
            }}
            placeholder="Ask a question about your sources..."
            className="flex-1 rounded-lg border bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-ring"
          />

          <button
            type="button"
            onClick={handleSend}
            className="rounded-lg bg-primary px-5 py-3 text-sm font-medium text-primary-foreground hover:opacity-90"
          >
            Send
          </button>
        </div>
      </div>
    </div>
  );
}