"use client";

import { useState } from "react";
import ChatInput from "./ChatInput";
import ChatMessage from "./ChatMessage";

interface Message {
  id: number;
  role: "user" | "assistant";
  content: string;
  source?: {
    title: string;
    page: number;
  };
}

const initialMessages: Message[] = [
  {
    id: 1,
    role: "assistant",
    content:
      "Hello! I can answer questions based on the documents in this notebook.",
    source: {
      title: "Java Fundamentals.pdf",
      page: 1,
    },
  },
];

export default function ChatWindow() {
  const [messages, setMessages] =
    useState<Message[]>(initialMessages);

  const [input, setInput] = useState("");

  const [isLoading, setIsLoading] = useState(false);

  function handleSend() {
    const trimmedInput = input.trim();

    if (!trimmedInput || isLoading) {
      return;
    }

    const userMessage: Message = {
      id: Date.now(),
      role: "user",
      content: trimmedInput,
    };

    setMessages((currentMessages) => [
      ...currentMessages,
      userMessage,
    ]);

    setInput("");

    setIsLoading(true);

    setTimeout(() => {
      const assistantMessage: Message = {
        id: Date.now() + 1,
        role: "assistant",
        content:
          "This is a demo response. Later, this message will be generated by our RAG system using the documents in this notebook.",
        source: {
          title: "Java Fundamentals.pdf",
          page: 12,
        },
      };

      setMessages((currentMessages) => [
        ...currentMessages,
        assistantMessage,
      ]);

      setIsLoading(false);
    }, 3000);
  }

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="flex-1 overflow-auto p-6">
        <div className="mx-auto max-w-3xl space-y-6">
          {messages.map((message) => (
            <ChatMessage
              key={message.id}
              role={message.role}
              content={message.content}
              source={message.source}
            />
          ))}

          {isLoading && (
            <div className="flex gap-3">
              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border bg-muted">
                AI
              </div>

              <div className="rounded-2xl border bg-card px-4 py-3 text-sm text-muted-foreground">
                Generating response...
              </div>
            </div>
          )}
        </div>
      </div>

      <ChatInput
        value={input}
        onChange={setInput}
        onSend={handleSend}
        isLoading={isLoading}
      />
    </div>
  );
}